package com.cniao5.wechat.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONTACT.
 */
public class Contact {

    private Long id;
    private long memberid;
    private long contactid;
    /** Not-null value. */
    private String email;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String headbig;
    /** Not-null value. */
    private String headmid;
    /** Not-null value. */
    private String headsmall;
    /** Not-null value. */
    private java.util.Date registetime;
    /** Not-null value. */
    private java.util.Date createtime;
    /** Not-null value. */
    private String pinyin;

    public Contact() {
    }

    public Contact(Long id) {
        this.id = id;
    }

    public Contact(Long id, long memberid, long contactid, String email, String name, String headbig,
                   String headmid, String headsmall, java.util.Date registetime, java.util.Date createtime, String pinyin) {
        this.id = id;
        this.memberid = memberid;
        this.contactid = contactid;
        this.email = email;
        this.name = name;
        this.headbig = headbig;
        this.headmid = headmid;
        this.headsmall = headsmall;
        this.registetime = registetime;
        this.createtime = createtime;
        this.pinyin = pinyin;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getMemberid() {
        return memberid;
    }

    public void setMemberid(long memberid) {
        this.memberid = memberid;
    }

    public long getContactid() {
        return contactid;
    }

    public void setContactid(long contactid) {
        this.contactid = contactid;
    }

    /** Not-null value. */
    public String getEmail() {
        return email;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmail(String email) {
        this.email = email;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getHeadbig() {
        return headbig;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHeadbig(String headbig) {
        this.headbig = headbig;
    }

    /** Not-null value. */
    public String getHeadmid() {
        return headmid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHeadmid(String headmid) {
        this.headmid = headmid;
    }

    /** Not-null value. */
    public String getHeadsmall() {
        return headsmall;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHeadsmall(String headsmall) {
        this.headsmall = headsmall;
    }

    /** Not-null value. */
    public java.util.Date getRegistetime() {
        return registetime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRegistetime(java.util.Date registetime) {
        this.registetime = registetime;
    }

    /** Not-null value. */
    public java.util.Date getCreatetime() {
        return createtime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatetime(java.util.Date createtime) {
        this.createtime = createtime;
    }

    /** Not-null value. */
    public String getPinyin() {
        return pinyin;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

}
