package com.cniao5.wechat.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.cniao5.wechat.model.Contact;
import com.cniao5.wechat.model.RequestMsg;
import com.cniao5.wechat.model.ChatMsg;

import com.cniao5.wechat.dao.ContactDao;
import com.cniao5.wechat.dao.RequestMsgDao;
import com.cniao5.wechat.dao.ChatMsgDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contactDaoConfig;
    private final DaoConfig requestMsgDaoConfig;
    private final DaoConfig chatMsgDaoConfig;

    private final ContactDao contactDao;
    private final RequestMsgDao requestMsgDao;
    private final ChatMsgDao chatMsgDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        requestMsgDaoConfig = daoConfigMap.get(RequestMsgDao.class).clone();
        requestMsgDaoConfig.initIdentityScope(type);

        chatMsgDaoConfig = daoConfigMap.get(ChatMsgDao.class).clone();
        chatMsgDaoConfig.initIdentityScope(type);

        contactDao = new ContactDao(contactDaoConfig, this);
        requestMsgDao = new RequestMsgDao(requestMsgDaoConfig, this);
        chatMsgDao = new ChatMsgDao(chatMsgDaoConfig, this);

        registerDao(Contact.class, contactDao);
        registerDao(RequestMsg.class, requestMsgDao);
        registerDao(ChatMsg.class, chatMsgDao);
    }
    
    public void clear() {
        contactDaoConfig.getIdentityScope().clear();
        requestMsgDaoConfig.getIdentityScope().clear();
        chatMsgDaoConfig.getIdentityScope().clear();
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public RequestMsgDao getRequestMsgDao() {
        return requestMsgDao;
    }

    public ChatMsgDao getChatMsgDao() {
        return chatMsgDao;
    }

}
